repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: check-toml # Check toml files for parseable syntax.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
          - id: forbid-new-submodules # Check for git submodules

    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8

    - repo: https://github.com/bwhmather/ssort
      rev: v0.10.2
      hooks:
          - id: ssort

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.7.1
      hooks:
          - id: reorder-python-imports
            args: [--py39-plus]

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
          - id: pyupgrade
            args: [--py39-plus, --keep-runtime-typing]

    - repo: https://github.com/codespell-project/codespell
      rev: v2.1.0
      hooks:
          - id: codespell
            args: ["-L", "reson,noe,2st,3st,ba,ser"]

    - repo: https://github.com/psf/black
      rev: 22.1.0 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
          - id: black
            language_version: python3.9
