[tool.poetry]
name = "chemex"
version = "2021.4.0-dev6"
description = "ChemEx is an analysis program for chemical exchange detected by NMR"
authors = ["Guillaume Bouvignies <gbouvignies@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/gbouvignies/chemex"
homepage = "https://github.com/gbouvignies/chemex"
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
]

  [tool.poetry.dependencies]
  python      = "=3.9"
  numpy       = "^1.21.5"
  scipy       = "^1.7.3"
  matplotlib  = "^3.5.1"
  lmfit       = "^1.0.3"
  toml        = "^0.10.2"
  Levenshtein = "^0.16.0"
  pydantic    = "^1.8.2"
  cachetools  = "^5.0.0"

  [tool.poetry.dev-dependencies]
  black                    = "^21.12b0"
  pre-commit               = "^2.16.0"
  flake8                   = "^4.0.1"
  recommonmark             = "^0.7.1"
  sphinx-rtd-theme         = "^0.5.2"
  sphinxcontrib-httpdomain = "^1.7.0"
  Sphinx                   = "^4.0.2"
  mypy                     = "^0.910"
  devtools                 = "^0.8.0"
  rich                     = "^10.15.2"
  wily                     = "^1.20.0"
  vulture                  = "^2.3"
  types-toml = "^0.10.4"
  types-cachetools = "^4.2.9"

  [tool.poetry.scripts]
  chemex = "chemex.chemex:main"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
plugins = ["pydantic.mypy", "numpy.typing.mypy_plugin"]

[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
